apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
  labels:
    app: customer-api
spec:
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: app
          env:
            - name: DB_URL
              value: "jdbc:postgresql://$DB_HOSTNAME:5432/$DB_DATABASE"
            - name: DB_USERNAME
              value: "$DB_USERNAME"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
            - name: SPRING_PROFILES_ACTIVE
              value: "$ENVIRONMENT"
          image: fiap7soat30/customer-api:$VERSION
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 2
          resources:
            requests:
              cpu: "20m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "3Gi"
      restartPolicy: Always